{{- if .Values.useJob }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-cluster-info-job-{{ randAlphaNum 5 | trunc 5 }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-events.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "kube-events.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube-events.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - {key: observeinc.com/unschedulable, operator: DoesNotExist}
                - {key: kubernetes.io/os, operator: NotIn, values: [windows]}
      containers:
        - name: kube-cluster-info
          image: {{ .Values.image.kube_cluster_info.repository }}:{{ default .Chart.AppVersion .Values.image.kube_cluster_info.tag }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - secretRef:
                name: credentials
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: OnFailure
{{- end }}
