{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-events.fullname" . }}
rules:
  - apiGroups:
      - ""
      - "apps"
      - "autoscaling"
      - "batch"
      - "networking.k8s.io"
    verbs:
      - "list"
      - "get"
      - "watch"
    resources:
      - "*"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-events.fullname" . }}
  labels:
    {{- include "kube-events.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-events.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-events.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-events.fullname" . }}
rules:
  - apiGroups: [""]
    verbs: ["create", "get"]
    resources:
      - configmaps

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-events.fullname" . }}
  labels:
    {{- include "kube-events.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-events.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-events.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end}}
