apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-sidecar-role
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - namespaces
      - pods
    verbs: ["get", "list", "watch"]

  - apiGroups: ["apps"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-sidecar-role-binding
subjects:
- kind: ServiceAccount
  name: my-otel-demo
  namespace: demo-fargate
roleRef:
  kind: ClusterRole
  name: otel-sidecar-role
  apiGroup: rbac.authorization.k8s.io
