agent:
  config:
    forwarder:
      processors:
        attributes/debug_source_statsd_metrics:
          actions:
          - action: insert
            key: debug_source
            value: statsduds
      receivers:
        statsd/uds:
          aggregation_interval: 60s
          enable_metric_type: true
          endpoint: ///var/run/obssocket/statsd.socket
          is_monotonic_counter: true
          transport: unixgram
      service:
        pipelines:
          metrics/custom:
            exporters:
            - prometheusremotewrite/observe
            processors:
            - memory_limiter
            - k8sattributes
            - batch
            - resourcedetection/cloud
            - resource/observe_common
            - attributes/debug_source_statsd_metrics
            - deltatocumulative
            receivers:
            - statsd/uds
forwarder:
  extraVolumeMounts:
    - mountPath: /var/run/obssocket
      name: obssocket

  extraVolumes:
    - hostPath:
        path: /tmp
      name: obssocket
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "sleep 20 && chmod o+rwx /var/run/obssocket/statsd.socket"]