agent:
  config:
    forwarder:
      processors:
        attributes/debug_source_statsd_metrics:
          actions:
          - action: insert
            key: debug_source
            value: statsduds
      receivers:
        statsd/uds:
          aggregation_interval: 60s
          enable_metric_type: true
          endpoint: ///var/run/obssocket/statsd.socket
          is_monotonic_counter: true # Sets all counter type metrics received as monotonic. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/statsdreceiver/README.md
          transport: unixgram
      service:
        pipelines:
          metrics/custom:
            exporters:
            - prometheusremotewrite/observe
            processors:
            - memory_limiter
            - k8sattributes
            - batch
            - resourcedetection/cloud
            - resource/observe_common
            - attributes/debug_source_statsd_metrics
            - deltatocumulative # It converts metrics from delta temporality to cumulative. https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/deltatocumulativeprocessor/README.md
            receivers:
            - statsd/uds
forwarder:
  extraVolumeMounts:
    - mountPath: /var/run/obssocket
      name: obssocket

  extraVolumes:
    - hostPath:
        path: /tmp
      name: obssocket
  # This postStart lifecycle hook waits for 20 seconds after container creation, then changes. For more details on lifecycle hooks see: https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/
  lifecycleHooks:
    postStart:
      exec:
        command: ["/bin/sh", "-c", "sleep 20 && chmod o+rwx /var/run/obssocket/statsd.socket"]
