apiVersion: v2
name: traces
description: Observe traces collection
type: application
version: 0.1.0
dependencies:
  - name: opentelemetry-collector
    version: 0.49.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: traces.enabled
