apiVersion: apps/v1
kind: Deployment
metadata:
  name: exception-generator-java
  labels:
    app: exception-generator-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exception-generator-java
  template:
    metadata:
      labels:
        app: exception-generator-java
    spec:
      containers:
      - name: exception-generator-java
        image: public.ecr.aws/d0l9o1t8/exception-generator:java_latest
        imagePullPolicy: IfNotPresent
