agent:
  config:
    nodeLogsMetrics:
      receivers:
        filelog:
          exclude:
          - "/var/log/pods/default_exception-generator-java-*_*/*/*.log"
          - '**/*.gz'
          - '**/*.tmp'
        filelog/java:
          exclude_older_than: 24h
          include:
          - "/var/log/pods/default_exception-generator-java-*_*/*/*.log"
          include_file_name: false
          include_file_path: true
          operators:
          - type: container
          - type: recombine
            combine_field: body
            is_first_entry: body matches "^\\d{4}-\\d{2}-\\d{2}\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d{3}"
            source_identifier: attributes["log.file.path"]
          poll_interval: 20ms
          retry_on_failure:
            enabled: true
            initial_interval: 1s
            max_elapsed_time: 5m
            max_interval: 30s
          start_at: end
          storage: file_storage
      service:
        pipelines:
          logs:
            receivers:
            - filelog/java
            - filelog
            processors:
            - memory_limiter
            - k8sattributes
            - batch
            - resourcedetection/cloud
            - resource/observe_common
            - attributes/debug_source_pod_logs
            exporters:
            - otlphttp/observe/base
