{{- if .Values.observe.token.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: otel-credentials
type: Opaque
data:
  OBSERVE_TOKEN: {{ .Values.observe.token.value | b64enc | quote }}
{{- end}}
