apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observe-agent-cluster-role
  labels:
    app.kubernetes.io/name: observe-agent-cluster-role
    app.kubernetes.io/instance: observe-agent
 
rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
  - apiGroups:
    - ""
    - '*'
    - apps
    - authorization.k8s.io
    - autoscaling
    - batch
    - networking.k8s.io
    - events.k8s.io
    - rbac.authorization.k8s.io
    - storage.k8s.io
    - vpcresources.k8s.aws
    resources:
    - '*'
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observe-agent-cluster-role-binding
  labels:
    app.kubernetes.io/name: observe-agent-cluster-role-binding
    app.kubernetes.io/instance: observe-agent
    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observe-agent-cluster-role
subjects:
- kind: ServiceAccount
  name: observe-agent-service-account
  namespace: observe