apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-cluster-metrics
  namespace: {{ template "observe-agent.namespace" . }}
data:
  relay: |
      {{- include "observe.deployment.clusterMetrics.config" . | nindent 4 -}}
