{{ if .Values.agent.selfMonitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-agent-monitor
  namespace: {{ template "observe-agent.namespace" . }}
data:
  relay: |
      {{- include "observe.deployment.agentMonitor.config" . | nindent 4 -}}
{{ end -}}
