apiVersion: v1
kind: ConfigMap
metadata:
  name: deployment-cluster-events
  namespace: {{ template "observe-agent.namespace" . }}
data:
  relay: |
      {{- include "observe.deployment.clusterEvents.config" . | nindent 4 -}}
