{{- if or .Values.observe.token.create .Values.observe.entityToken.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: agent-credentials
type: Opaque
data:
  {{- if .Values.observe.token.create }}
  OBSERVE_TOKEN: {{ .Values.observe.token.value | b64enc | quote }}
  {{- end}}
  {{- if .Values.observe.traceToken.create }}
  TRACE_TOKEN: {{ .Values.observe.traceToken.value | b64enc | quote }}
  {{- end}}
{{- end}}
