{{- if or .Values.observe.token.create .Values.observe.entityToken.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: agent-credentials
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.observe.token.create }}
  OBSERVE_TOKEN: {{ .Values.observe.token.value | b64enc | quote }}
  {{- end}}
  {{- if .Values.observe.entityToken.create }}
  ENTITY_TOKEN: {{ .Values.observe.entityToken.value | b64enc | quote }}
  {{- end}}
{{- end}}
