global:
  observe:
    customer: ""
    collectorScheme: https
    collectorHost: collect.observeinc.com
    collectorPort: 443

events:
  enabled: true

metrics:
  enabled: true

logs:
  enabled: true
