global:
  observe:
    customer: ""
    collectorScheme: https
    collectorHost: collect.observeinc.com
    collectorPort: 443

observe:
  secret:
    create: true
    token:

# see the values.yaml files in the subcharts for overrideable values.
events:
  enabled: true

metrics:
  enabled: true

logs:
  enabled: true
