cluster:
  name: observe-agent-monitored-cluster
  events:
    pullInterval: 20m
    enabled: true
  metrics:
    enabled: true

  namespaceOverride:
    value: k8smonitoring

application:
  # use this option to scrape prometheus metrics from pods
  prometheusScrape:
    enabled: true
    interval: 10s
    # namespaces to exclude from scraping
    namespaceDropRegex: (.*istio.*|.*ingress.*|kube-system)
    # namespaces to explicity include for scraping - can use or (ns1|ns2)
    namespaceKeepRegex: (default)
    # port names to scrape from - can use or .*metrics|otherportname
    portKeepRegex: .*metrics|web
    # metrics to drop
    metricDropRegex: .*bucket
    # metrics to keep
    metricKeepRegex: (.*)



containers:
  logs:
    enabled: true
  metrics:
    enabled: false

agent:
  selfMonitor:
    enabled: true

config:
global:
  debug:
    verbosity: normal

cluster-events:
  enabled: true
  namespaceOverride: "k8smonitoring"
  tolerations:
  - key: "deployObserve"
    operator: "Equal"
    value: "notAllowed"
    effect: "NoSchedule"

cluster-metrics:
  enabled: true
  namespaceOverride: "k8smonitoring"

node-logs-metrics:
  enabled: true
  namespaceOverride: "k8smonitoring"


monitor:
  enabled: true
  namespaceOverride: "k8smonitoring"
