apiVersion: v2
name: events
description: Observe kubernetes event collection
type: application
version: 0.1.8
appVersion: v0.9.1
dependencies:
  - name: endpoint
    version: 0.1.3
    repository: file://../endpoint
