global:
  observe:
    collectionEndpoint: ""

observe:
  token:
    value: ""

opentelemetry-collector:
  mode: deployment
  replicaCount: 10
  resources:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
