global:
  observe:
    collectionEndpoint: ""

observe:
  token:
    value: ""

opentelemetry-collector:
  resources:
    limits:
      cpu: 50m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
