global:
  observe:
    collectionEndpoint: "http://test-stack-collector.testing.svc.cluster.local:8080"

observe:
  token:
    create: true
    value: "fake-token"

proxy:
  nameOverride: collector
  enabled: true
  image:
    repository: test-collector
    tag: latest
