events:
  resources:
    limits:
      cpu: 400m
      memory: 2Gi
    requests:
      cpu: 400m
      memory: 2Gi

logs:
  fluent-bit:
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 500m
        memory: 256Mi
    config:
      mem_buf_limit: 30MB

metrics:
  grafana-agent:
    prom_config:
      host_filter: "true"
    controller:
      type: daemonset
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: "20%"
      tolerations:
        - operator: Exists
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - {key: observeinc.com/unschedulable, operator: DoesNotExist}
                  - {key: eks.amazonaws.com/compute-type, operator: NotIn, values: [fargate]}
                  - {key: kubernetes.io/os, operator: NotIn, values: [windows]}

    agent:
      resources:
        limits:
          cpu: 200m
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 1Gi
