global:
  observe:
    collectionEndpoint: ""

observe:
  token:
    value: ""

events:
  resources:
    limits:
      cpu: 200m
      memory: 1Gi
    requests:
      cpu: 200m
      memory: 1Gi

logs:
  fluent-bit:
    resources:
      limits:
        cpu: 200m
        memory: 192Mi
      requests:
        cpu: 200m
        memory: 192Mi
    config:
      mem_buf_limit: 20MB

metrics:
  grafana-agent:
    agent:
      resources:
        limits:
          cpu: 500m
          memory: 4Gi
        requests:
          cpu: 500m
          memory: 4Gi
