name: Helm Charts Agent - Integration Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main


#Special permissions required for OIDC authentication
permissions:
    id-token: write
    contents: write
    pull-requests: write

env:
    TF_VAR_observe_url: ${{secrets.OBSERVE_URL}}
    TF_VAR_observe_token: ${{secrets.OBSERVE_TOKEN}}
    TF_VAR_helm_chart_agent_test_release_name: helm-charts-agent-gha-integration-tests


jobs:

  helm-charts-agent-integration-tests:
    name: helm-charts-agent-integration-tests-${{ matrix.namespace }}-${{ matrix.values }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          values:
            - default.yaml
          namespace:
            - observe
          include: # Test not-observe namespace with default values only
            - values: default.yaml
              namespace: not-observe
    defaults:
        run:
            working-directory: integration #Terrafrom commands and tests are ran from integration directory
    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Terraform Variables for matrixing
          run:  |
            echo "TF_VAR_helm_chart_agent_test_values_file=$(echo ${{matrix.values}})" >> $GITHUB_ENV
            echo "TF_VAR_helm_chart_agent_test_namespace=$(echo ${{matrix.namespace}})" >> $GITHUB_ENV

        - uses: azure/setup-kubectl@v4
          with:
            version: latest

        - name: Setup Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'

        - run: pip install -r scripts/requirements.txt

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.9.5

        - name: Terraform Init
          id: init
          run: terraform init

        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform Test
          id: test
          run: |
            terraform test -verbose
