deployment:
  # Resource settings
  deployment:
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
daemonset:
  daemonset:
    # Resource settings
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi

observeAgent: |
  token: {{OBSERVE_TOKEN}}

  observe_url: {{OBSERVE_COLLECTION_URL}}

  debug: false

  host_monitoring:
    enabled: false
    logs:
      enabled: false
    metrics:
      enabled: false

  otel_config_overrides:
    extensions:
      health_check:
        endpoint: '${env:MY_POD_IP}:13133'
