observe:
  token:
  collectionEndpoint:

deployment-cluster-events:
  deployment-cluster-events:
    # Resource settings
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
daemonset:
  daemonset:
    # Resource settings
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
