deployment-cluster-events:
  deployment-cluster-events:
    # Resource settings
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
daemonset:
  daemonset:
    # Resource settings
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 256Mi
